
##Docker compose for VPS usage (opened ports on internet by reverse-proxy nginx)

## COMMANDE A FAIRE : docker compose -f docker-compose.yaml up -d

services:
  
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak:/opt/keycloak/
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT_BACKCHANNEL: ${KC_HOSTNAME_STRICT_BACKCHANNEL}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_LOG_LEVEL: info
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KC_CONTAINER_NAME}:5432/${KC_DB}
      KC_DB_USERNAME: ${KC_USER}
      KC_DB_PASSWORD: ${KC_PASSWORD}
    depends_on:
      - ${KC_CONTAINER_NAME}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7080/health/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 15
    command: ["start", "--http-port", "7080", "--https-port", "7443"]
    networks:
      - LAN

  kc_db:
    user: "root"
    container_name: "${KC_CONTAINER_NAME}"
    image: postgres:15.15
    volumes:
      - kc_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KC_DB}
      POSTGRES_USER: ${KC_USER}
      POSTGRES_PASSWORD: ${KC_PASSWORD}
    networks:
      - LAN
  db:
    user: "root"
    container_name: "db"
    image: postgres:15.15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - LAN


  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: sdmis-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${PORT_PG}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "${PORT_RABBITMQ_TECHNIQUE}"
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      DECISION_EVENT_QUEUE: decision.events
      DECISION_INTERVENTION_QUEUE: decision.interventions
    networks:
      - LAN
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - LAN
  
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - LAN
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rmq-data:/var/lib/rabbitmq/mnesia/
    networks:
      - LAN
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  decision-engine:
    build: ./backend/MoteurDecision
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "${PORT_RABBITMQ_TECHNIQUE}"
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      DECISION_EVENT_QUEUE: decision.events
      DECISION_INTERVENTION_QUEUE: decision.interventions
      SDMIS_API_URL: http://sdmis-api:8080
      KEYCLOAK_TOKEN_URL: http://keycloak:7080/realms/SDMIS/protocol/openid-connect/token
      KEYCLOAK_CLIENT_ID: sdmis-moteur-decision
      KEYCLOAK_CLIENT_SECRET: sOnT5y8kAPCg52iTcvAJ1Vxt20umsECq
    networks:
      - LAN

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/conf.d
      - certbot_cert:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - LAN

  certbot:
    image: certbot/certbot
    container_name: certbot    
    restart: always
    volumes:
      - certbot_cert:/var/www/certbot
      - certbot_conf:/etc/letsencrypt


volumes:
  keycloak:
  kc_db_data:
  db_data:
  pgadmin-data:
  rmq-data:
  certbot_conf:
  certbot_cert:
  nginx:
networks:
  LAN:
