services:
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak:/opt/keycloak/
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
      - "9000:9000"
    networks:
      - bridge_network
  db:
    user: "root"
    container_name: "db"
    image: postgres:15.15
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - bridge_network
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - bridge_network
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
volumes:
  keycloak:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./KEYCLOAK/WEB
  data_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./PG
  pgadmin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./PG_ADMIN
networks:
  bridge_network:
    driver: bridge
