
##Docker compose for VPS usage (opened ports on internet by reverse-proxy nginx)

## COMMANDE A FAIRE : docker compose -f docker-compose.yaml up -d

services:
  
  keycloak:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak:/opt/keycloak/
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${PORT_INT_KEYCLOAK}
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_LOG_LEVEL: info
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: forwarded
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_INT_KEYCLOAK}/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "${PORT_EXT_KEYCLOAK}", "--https-port", "7443"]
    networks:
      - LAN
  
  db:
    user: "root"
    container_name: "db"
    image: postgres:15.15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - LAN

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: sdmis-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${PORT_PG}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ""
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "${PORT_RABBITMQ_TECHNIQUE}"
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      DECISION_EVENT_QUEUE: decision.events
      DECISION_INTERVENTION_QUEUE: decision.interventions
    networks:
      - LAN
  
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - LAN
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rmq-data:/var/lib/rabbitmq/mnesia/
    networks:
      - LAN
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  decision-engine:
    build: ./backend/MoteurDecision
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "${PORT_RABBITMQ_TECHNIQUE}"
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      DECISION_EVENT_QUEUE: decision.events
      DECISION_INTERVENTION_QUEUE: decision.interventions
      SDMIS_API_URL: http://sdmis-api:8080
    networks:
      - LAN

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/conf.d
      - certbot_cert:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - LAN

  certbot:
    image: certbot/certbot
    container_name: certbot    
    restart: always
    volumes:
      - certbot_cert:/var/www/certbot
      - certbot_conf:/etc/letsencrypt

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonar
      SONAR_JDBC_USERNAME: "${SONAR_USERNAME}"
      SONAR_JDBC_PASSWORD: "${SONAR_PASSWORD}"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  sonarqube_db:
    image: postgres:15
    container_name: sonarqube_db 
    environment:
      POSTGRES_USER: "${SONAR_DB_USERNAME}"
      POSTGRES_PASSWORD: "${SONAR_DB_PASSWORD}"
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keycloak:
  db_data:
  pgadmin-data:
  rmq-data:
  certbot_conf:
  certbot_cert:
  nginx:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_postgres:
networks:
  LAN: