name: Deploy to VPS Stable Version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.4
        env:
          VPS_PATH: ${{ secrets.VPS_PROJECT_PATH }}
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USER_USERNAME }}
          password: ${{ secrets.VPS_USER_PASSWORD }}
          key: ${{ secrets.VPS_USER_SSH_KEY }}
          script: |
            set -e
            cd "$VPS_PATH"
            ls -la
            git switch main
            git pull origin main
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml up -d --build
