name: DAST - ZAP (docker-compose local)

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Start docker-compose (local)
        run: |
          docker compose \
            --env-file .env.ci \
            -f docker-compose.yaml.local \
            up -d --build

      - name: Wait for API
        run: |
          echo "Waiting for API..."          
          sleep 30


      - name: ZAP Baseline Scan (API)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a -J zap.json'
          rules_file_name: '.zap/rules.tsv'

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_report.html
            zap.json

      - name: Stop docker-compose
        if: always()
        run: |
          docker compose \
            -f docker-compose.yaml.local \
            down -v
