name: DAST - ZAP (docker-compose local)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "dev"]


jobs:
  dast:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Start docker-compose (local)
        run: |
          docker compose \
            --env-file .env.ci \
            -f docker-compose.yaml.local \
            up -d --build frontend api db 

      - name: Wait for API
        run: |
          echo "Waiting for API..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8080/v3/api-docs > /dev/null; then
              echo "API is ready"
              break
            fi
            sleep 5
          done

      - name: Wait for FRONTEND
        run: |
          echo "Waiting for FRONTEND..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:5173 > /dev/null; then
              echo "FRONTEND is ready"
              break
            fi
            sleep 5
          done

      - name: Fix workspace permissions
        run: sudo chmod -R 777 ${{ github.workspace }}

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: ''
          format: openapi
          target: 'http://127.0.0.1:8080/v3/api-docs'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: >
            -J zap_api.json
            -r zap_api.html
        
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-API-report
          path: |
            zap_api.json
            zap_api.html

      - name: remove common files of ZAP for FRONTEND
        run: |
          ls -al
          whoami
          pwd          
          sudo chmod 777 -R *
          ls -al 
          rm report_md.md
          ls -al

      - name: ZAP Baseline Scan (FRONTEND)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            -t ghcr.io/zaproxy/zaproxy:stable \
            --network="host" \
            zap-baseline.py \
            -t http://127.0.0.1:5173 \
            -c .zap/rules.tsv \
            -r zap_frontend.html \
            -j zap_frontend.json \
            -I

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-frontend-report
          path: |
            zap_frontend.html
            zap_frontend.json
            zap-frontend.md

      - name: Stop docker-compose
        if: always()
        run: |
          docker compose \
            --env-file .env.ci \
            -f docker-compose.yaml.local \
            down -v
