name: DAST - ZAP (docker-compose local)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "dev"]


jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Start docker-compose (local)
        run: |
          docker compose \
            --env-file .env.ci \
            -f docker-compose.yaml.local \
            up -d --build

      - name: Wait for API
        run: |
          echo "Waiting for API..."          
          sleep 30

      - name: Fix workspace permissions
        run: sudo chmod -R a+w $GITHUB_WORKSPACE

      - name: ZAP Baseline Scan (API)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://127.0.0.1:8080'
          cmd_options: >
            -a
            -J zap_api.json
            -r zap_api.html
            -d failOnRisk HIGH
          rules_file_name: '.zap/rules.tsv'
          fail_action: true
          
      - name: ZAP Baseline Scan (FRONTEND)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://127.0.0.1:5173'
          cmd_options: >
            -a
            -J zap_frontend.json
            -r zap_frontend.html
            -d failOnRisk HIGH
          rules_file_name: '.zap/rules.tsv'
          fail_action: true

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_frontend.html
            zap_frontend.json
            zap_api.html
            zap_api.json

      - name: Stop docker-compose
        if: always()
        run: |
          docker compose \
            --env-file .env.ci \
            -f docker-compose.yaml.local \
            down -v
